/*
 * YearStatisticsFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.insigma.dish.gui;

import java.awt.Font;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.StandardChartTheme;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

import com.insigma.dish.dao.db.DAOFactory;
import com.insigma.dish.util.Utils;

/**
 *
 * @author  __USER__
 */
public class YearStatisticsFrame extends javax.swing.JInternalFrame {

	/** Creates new form YearStatisticsFrame */
	public YearStatisticsFrame() {
		initComponents();
		qryYearStatis((String)jComboYear.getSelectedItem());
	}
	private JPanel jPanel = null;
	private JFreeChart jfreeChart = null;
	private DefaultCategoryDataset dataset = null;
	private List<Map<String, Object>> mapList = null;
	private void qryYearStatis(String year) {
		//设置主题
		Utils.setChartTheme();
		//设置数据集
		setDataSet(year);
		//创建图
		jfreeChart = ChartFactory.createBarChart3D("年度交易统计图", // 图表标题
				"月份", // 目录轴的显示标签
				"交易额", // 数值轴的显示标签
				(CategoryDataset) dataset, // 数据集
				PlotOrientation.VERTICAL, // 图表方向：水平、垂直
				true, // 是否显示图例(对于简单的柱状图必须是false)
				false, // 是否生成工具
				false // 是否生成URL链接, categoryAxisLabel, valueAxisLabel, dataset
				);
		
		//显示
		jPanel = new ChartPanel(jfreeChart);
		((BasicInternalFrameUI) jInternalFrameShowImg.getUI())
				.setNorthPane(null);
		jInternalFrameShowImg.setContentPane(jPanel);

	}

	private void setDataSet(String year) {
		mapList = DAOFactory.createOrderDao().yearStatis(
				year);

		dataset = new DefaultCategoryDataset();
		if(mapList!=null && mapList.size()>0){
			for (Map<String, Object> data : mapList) {
				dataset.addValue(((BigDecimal) data.get("month1")).doubleValue(),
						"月份", "1月");
				dataset.addValue(((BigDecimal) data.get("month2")).doubleValue(),
						"月份", "2月");
				dataset.addValue(((BigDecimal) data.get("month3")).doubleValue(),
						"月份", "3月");
				dataset.addValue(((BigDecimal) data.get("month4")).doubleValue(),
						"月份", "4月");
				dataset.addValue(((BigDecimal) data.get("month5")).doubleValue(),
						"月份", "5月");
				dataset.addValue(((BigDecimal) data.get("month6")).doubleValue(),
						"月份", "6月");
				dataset.addValue(((BigDecimal) data.get("month7")).doubleValue(),
						"月份", "7月");
				dataset.addValue(((BigDecimal) data.get("month8")).doubleValue(),
						"月份", "8月");
				dataset.addValue(((BigDecimal) data.get("month9")).doubleValue(),
						"月份", "9月");
				dataset.addValue(((BigDecimal) data.get("month10")).doubleValue(),
						"月份", "10月");
				dataset.addValue(((BigDecimal) data.get("month11")).doubleValue(),
						"月份", "11月");
				dataset.addValue(((BigDecimal) data.get("month12")).doubleValue(),
						"月份", "12月");
			}
		}
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jComboYear = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jButtonQry = new javax.swing.JButton();
		jInternalFrameShowImg = new javax.swing.JInternalFrame();

		setClosable(true);

		jComboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"2014", "2013", "2012", "2011" }));

		jLabel1.setText("\u5e74\u4efd\uff1a");

		jButtonQry.setText("\u67e5\u8be2");
		jButtonQry.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonQryActionPerformed(evt);
			}
		});

		jInternalFrameShowImg.setVisible(true);

		javax.swing.GroupLayout jInternalFrameShowImgLayout = new javax.swing.GroupLayout(
				jInternalFrameShowImg.getContentPane());
		jInternalFrameShowImg.getContentPane().setLayout(
				jInternalFrameShowImgLayout);
		jInternalFrameShowImgLayout
				.setHorizontalGroup(jInternalFrameShowImgLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 526, Short.MAX_VALUE));
		jInternalFrameShowImgLayout
				.setVerticalGroup(jInternalFrameShowImgLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 329, Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(24, 24,
																		24)
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jComboYear,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButtonQry))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jInternalFrameShowImg)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														jComboYear,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButtonQry))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jInternalFrameShowImg)
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButtonQryActionPerformed(java.awt.event.ActionEvent evt) {
		setDataSet((String)jComboYear.getSelectedItem());
		CategoryPlot plot = (CategoryPlot)jfreeChart.getPlot();
		plot.setDataset(dataset);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonQry;
	private javax.swing.JComboBox jComboYear;
	private javax.swing.JInternalFrame jInternalFrameShowImg;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}