/*
 * QueryDish.java
 *
 * Created on __DATE__, __TIME__
 */

package com.insigma.dish.gui;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

import com.insigma.dish.dao.db.DAOFactory;
import com.insigma.dish.pojo.DishInfo;
import com.insigma.dish.pojo.DishSort;
import com.insigma.dish.pojo.TableInfo;

/**
 *
 * @author  __USER__
 */
public class DishQueryFrame extends javax.swing.JInternalFrame {

	/** Creates new form QueryDish */
	public DishQueryFrame() {
		initComponents();
		init();
	}
	private List<DishInfo> dishes;
	private void init() {
		dishes = DAOFactory.createDishDao().qryDishesAll();
		DefaultTableModel dModel = new DefaultTableModel(new String[] { "编号",
				"价格", "名称", "备注", "分类" }, 0);
		for (DishInfo dishInfo : dishes) {
			dModel.addRow(new String[] { String.valueOf(dishInfo.getDishID()),
					String.valueOf(dishInfo.getPrice()), dishInfo.getName(),
					dishInfo.getDemo(), dishInfo.getDishSort().getName() });
		}
		tabDish.setModel(dModel);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btnOk = new javax.swing.JButton();
		labTitle = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		scrpDish = new javax.swing.JScrollPane();
		tabDish = new javax.swing.JTable();

		setClosable(true);

		btnOk.setText("\u786e\u5b9a");
		btnOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOkActionPerformed(evt);
			}
		});

		labTitle.setFont(new java.awt.Font("微软雅黑", 1, 18));
		labTitle.setText("\u8bf7\u9009\u62e9\u83dc\u54c1\uff1a");

		tabDish.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "名称", "价格", "分类", "备注" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		scrpDish.setViewportView(tabDish);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(29, 29,
																		29)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						labTitle)
																				.addComponent(
																						jSeparator1)
																				.addComponent(
																						scrpDish,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						496,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(239,
																		239,
																		239)
																.addComponent(
																		btnOk)))
								.addContainerGap(23, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(9, 9, 9)
								.addComponent(labTitle)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(4, 4, 4)
								.addComponent(scrpDish,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										253,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(btnOk)
								.addContainerGap(46, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {
		int[] rows = tabDish.getSelectedRows();
		List<DishInfo> selectedDishes = new ArrayList<DishInfo>();
		for (int i : rows) {
			/*从表格中获取数据   要会
			 * DishInfo dish = new DishInfo();
			dish.setDishID((int)tabDish.getValueAt(i, 0));
			dish.setPrice((BigDecimal)tabDish.getValueAt(i, 1));
			dish.setName((String)tabDish.getValueAt(i, 2));
			dish.setDemo((String)tabDish.getValueAt(i, 3));
			dish.setDishSort(new DishSort(0, (String)tabDish.getValueAt(i, 4)));*/
			selectedDishes.add(dishes.get(i));
		}
		//改变 订单新增界面的   菜品列表显示
		changeOrderAddFrame(selectedDishes);
	}

	private void changeOrderAddFrame(List<DishInfo> selectedDishes) {
		//BigDecimal orderPrice = new BigDecimal(0.00);
		Double orderPrice = 0.00;
		//改变订单新增菜品列表
		JList<DishInfo> jListShowDish = orderAddFrame.getjListShowDish();
		DefaultListModel<DishInfo> dModel = new DefaultListModel<DishInfo>();
		for (DishInfo dish : selectedDishes) {
			dModel.addElement(dish);
			//价格累加
			orderPrice += dish.getPrice().doubleValue();
		}
		jListShowDish.setModel(dModel);
		//改变订单总价
		JTextField JTextFieldPrice = orderAddFrame.getjTextFieldOrderPrice();
		JTextFieldPrice.setText(String.valueOf(orderPrice));
		this.dispose();
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnOk;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JLabel labTitle;
	private javax.swing.JScrollPane scrpDish;
	private javax.swing.JTable tabDish;
	// End of variables declaration//GEN-END:variables
	private OrderAddFrame orderAddFrame;

	public void setOrderAddFrame(OrderAddFrame orderAddFrame) {
		this.orderAddFrame = orderAddFrame;
	}

}