/*
 * MyFirstFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.insigma.dish.gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.jvnet.substance.skin.SubstanceFieldOfWheatLookAndFeel;

import com.insigma.dish.dao.UserDao;
import com.insigma.dish.dao.db.DAOFactory;
import com.insigma.dish.pojo.EmployeInfo;
import com.insigma.dish.util.Utils;

/**
 *
 * @author  __USER__
 */
public class LoginFrame extends javax.swing.JFrame {

	/** Creates new form MyFirstFrame */
	public LoginFrame() {
		initComponents();
		setLocationRelativeTo(null);
		try {
			UIManager.setLookAndFeel(new SubstanceFieldOfWheatLookAndFeel());
		} catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		Utils.setTitleImage(this);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jComboBox1 = new javax.swing.JComboBox();
		jBtnLogin = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel1 = new javax.swing.JLabel();
		jTxtUserName = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jPassPassword = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u722a\u54c72\u70b9\u9910");

		jBtnLogin.setBackground(new java.awt.Color(255, 255, 255));
		jBtnLogin.setText("\u767b\u5f55");
		jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnLoginActionPerformed(evt);
			}
		});

		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		jTxtUserName.setText("\u6076\u9b54");

		jLabel2.setText("\u5bc6   \u7801\uff1a");

		jPassPassword.setText("1111");

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/sun/java/swing/plaf/motif/icons/Question.gif"))); // NOI18N

		jLabel4.setFont(new java.awt.Font("隶书", 0, 18));
		jLabel4.setText("\u722a\u54c72\u70b9\u9910\u7cfb\u7edf");

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/insigma/dish/images/Catch900003.jpg"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(48, 48,
																		48)
																.addComponent(
																		jLabel5,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		60,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jPassPassword)
																				.addComponent(
																						jTxtUserName,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						189,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(20, 20,
																		20)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jLabel4,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										296,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						jSeparator1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						356,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(157,
																		157,
																		157)
																.addComponent(
																		jBtnLogin)))
								.addContainerGap(30, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addGap(4,
																										4,
																										4)))
																.addGap(35, 35,
																		35)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel1)
																												.addComponent(
																														jTxtUserName,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel2)
																												.addComponent(
																														jPassPassword,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(38,
																										38,
																										38)
																								.addComponent(
																										jBtnLogin)
																								.addGap(3,
																										3,
																										3))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel5,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										59,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(63,
																										63,
																										63))))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jSeparator1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(149,
																		149,
																		149)))
								.addGap(48, 48, 48)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 登陆点击
	 * @param evt
	 */
	private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {
		//先根据用户名查询emp对象，然后判断 emp是否为null,是null表示用户不存，否则 再判断密码是否正确
		UserDao userDao = DAOFactory.createUserDao();
		EmployeInfo emp = userDao.qryEmpByName(jTxtUserName.getText());
		if (emp != null) {
			if (!jPassPassword.getText().equals(emp.getPwd())) {
				JOptionPane.showMessageDialog(this, "密码错,请重新输入");
			} else {
				MainFrame mainFrame = new MainFrame(emp);
				mainFrame.setVisible(true);
				this.dispose();

			}
		} else {
			JOptionPane.showMessageDialog(this, "用户名不存在,请重新输入");
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jBtnLogin;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPasswordField jPassPassword;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTxtUserName;
	// End of variables declaration//GEN-END:variables

}