/*
 * QueryTable.java
 *
 * Created on __DATE__, __TIME__
 */

package com.insigma.dish.gui;

import java.sql.SQLException;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

import com.insigma.dish.dao.db.DAOFactory;
import com.insigma.dish.pojo.TableInfo;

/**
 *
 * @author  __USER__
 */
public class TableQueryFrame extends javax.swing.JInternalFrame {

	/** Creates new form QueryTable */
	public TableQueryFrame() {
		initComponents();
		myInit();
	}

	private void myInit() {
		//查询table数据
		List<TableInfo> tables = DAOFactory.createTableDao().qryTablesAll();
		DefaultListModel<TableInfo> dModel = new DefaultListModel<TableInfo>();
		for (TableInfo tableInfo : tables) {
			dModel.addElement(tableInfo);
		}
		for (int i = 0; i < tables.size(); i++) {
			tables.get(i);
		}
		listTable.setModel(dModel);
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		listTable = new javax.swing.JList();
		labTitle = new javax.swing.JLabel();
		btnOk = new javax.swing.JButton();

		setClosable(true);

		listTable.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "例子：1号桌--可用", "例子：2号桌--可用" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(listTable);

		labTitle.setFont(new java.awt.Font("微软雅黑", 1, 18));
		labTitle.setText("\u8bf7\u9009\u62e9\u53ef\u7528\u9910\u684c\uff1a");

		btnOk.setText("\u786e\u5b9a");
		btnOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOkActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(51, 51,
																		51)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		257,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(29, 29,
																		29)
																.addComponent(
																		labTitle))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(147,
																		147,
																		147)
																.addComponent(
																		btnOk)))
								.addContainerGap(50, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(9, 9, 9)
								.addComponent(labTitle)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										104,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnOk)
								.addContainerGap(45, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {
		
		TableInfo table = (TableInfo)listTable.getSelectedValue();
		if(table!=null){
			if(table.getTableState()==0){
				orderAddFrame.getjLabelTableId().setText(String.valueOf(table.getTableID()));
				this.dispose();
			}else{
				JOptionPane.showMessageDialog(this, "桌子正在使用");
			}
		}else{
			JOptionPane.showMessageDialog(this, "请选择一个桌子");
		}
		
		
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnOk;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel labTitle;
	private javax.swing.JList listTable;
	// End of variables declaration//GEN-END:variables
	private OrderAddFrame orderAddFrame;
	public void setOrderAddFrame(OrderAddFrame orderAddFrame) {
		this.orderAddFrame = orderAddFrame;
	}
	

}